// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countStaff = `-- name: CountStaff :one
SELECT count(*)::bigint FROM staff_users
`

func (q *Queries) CountStaff(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStaff)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getStaffByEmail = `-- name: GetStaffByEmail :one
SELECT id, email, password_hash, role, created_at
FROM staff_users
WHERE email = $1
`

func (q *Queries) GetStaffByEmail(ctx context.Context, email string) (StaffUser, error) {
	row := q.db.QueryRow(ctx, getStaffByEmail, email)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const insertCapability = `-- name: InsertCapability :exec
INSERT INTO maker_capabilities (maker_id, category_slug)
VALUES ($1, $2)
`

type InsertCapabilityParams struct {
	MakerID      uuid.UUID `json:"maker_id"`
	CategorySlug string    `json:"category_slug"`
}

func (q *Queries) InsertCapability(ctx context.Context, arg InsertCapabilityParams) error {
	_, err := q.db.Exec(ctx, insertCapability, arg.MakerID, arg.CategorySlug)
	return err
}

const insertMaker = `-- name: InsertMaker :one
INSERT INTO makers (
    name, city, verification_date, moq_quantity, moq_basis, moq_basis_note,
    lead_time_estimate, price_min_idr, price_max_idr, price_note, conditions,
    enmasse_vendor_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, name, city, publication_status, verification_date, moq_quantity, moq_basis, moq_basis_note, lead_time_estimate, price_min_idr, price_max_idr, price_note, conditions, is_demo_fixture, enmasse_vendor_id, created_at, updated_at, hours_open, hours_close, service_area, hours_days, enmasse_user_id
`

type InsertMakerParams struct {
	Name             string       `json:"name"`
	City             string       `json:"city"`
	VerificationDate *time.Time   `json:"verification_date"`
	MoqQuantity      *int32       `json:"moq_quantity"`
	MoqBasis         NullMoqBasis `json:"moq_basis"`
	MoqBasisNote     *string      `json:"moq_basis_note"`
	LeadTimeEstimate *string      `json:"lead_time_estimate"`
	PriceMinIdr      *int32       `json:"price_min_idr"`
	PriceMaxIdr      *int32       `json:"price_max_idr"`
	PriceNote        *string      `json:"price_note"`
	Conditions       *string      `json:"conditions"`
	EnmasseVendorID  *uuid.UUID   `json:"enmasse_vendor_id"`
}

func (q *Queries) InsertMaker(ctx context.Context, arg InsertMakerParams) (Maker, error) {
	row := q.db.QueryRow(ctx, insertMaker,
		arg.Name,
		arg.City,
		arg.VerificationDate,
		arg.MoqQuantity,
		arg.MoqBasis,
		arg.MoqBasisNote,
		arg.LeadTimeEstimate,
		arg.PriceMinIdr,
		arg.PriceMaxIdr,
		arg.PriceNote,
		arg.Conditions,
		arg.EnmasseVendorID,
	)
	var i Maker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.PublicationStatus,
		&i.VerificationDate,
		&i.MoqQuantity,
		&i.MoqBasis,
		&i.MoqBasisNote,
		&i.LeadTimeEstimate,
		&i.PriceMinIdr,
		&i.PriceMaxIdr,
		&i.PriceNote,
		&i.Conditions,
		&i.IsDemoFixture,
		&i.EnmasseVendorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HoursOpen,
		&i.HoursClose,
		&i.ServiceArea,
		&i.HoursDays,
		&i.EnmasseUserID,
	)
	return i, err
}

const insertStaff = `-- name: InsertStaff :one
INSERT INTO staff_users (email, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, role, created_at
`

type InsertStaffParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) InsertStaff(ctx context.Context, arg InsertStaffParams) (StaffUser, error) {
	row := q.db.QueryRow(ctx, insertStaff, arg.Email, arg.PasswordHash, arg.Role)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminMakers = `-- name: ListAdminMakers :many
SELECT id, name, city, publication_status, enmasse_vendor_id, created_at
FROM makers
WHERE is_demo_fixture = FALSE
ORDER BY created_at DESC
`

type ListAdminMakersRow struct {
	ID                uuid.UUID         `json:"id"`
	Name              string            `json:"name"`
	City              string            `json:"city"`
	PublicationStatus PublicationStatus `json:"publication_status"`
	EnmasseVendorID   *uuid.UUID        `json:"enmasse_vendor_id"`
	CreatedAt         time.Time         `json:"created_at"`
}

func (q *Queries) ListAdminMakers(ctx context.Context) ([]ListAdminMakersRow, error) {
	rows, err := q.db.Query(ctx, listAdminMakers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminMakersRow{}
	for rows.Next() {
		var i ListAdminMakersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.PublicationStatus,
			&i.EnmasseVendorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permitContact = `-- name: PermitContact :exec
UPDATE maker_contacts
SET publish_permitted = TRUE, permission_at = NOW()
WHERE maker_id = $1
`

func (q *Queries) PermitContact(ctx context.Context, makerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, permitContact, makerID)
	return err
}

const replaceCapabilities = `-- name: ReplaceCapabilities :exec
DELETE FROM maker_capabilities WHERE maker_id = $1
`

func (q *Queries) ReplaceCapabilities(ctx context.Context, makerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, replaceCapabilities, makerID)
	return err
}

const setMakerEnmasseUserID = `-- name: SetMakerEnmasseUserID :exec
UPDATE makers
SET enmasse_user_id = $2, updated_at = NOW()
WHERE id = $1
`

type SetMakerEnmasseUserIDParams struct {
	ID            uuid.UUID  `json:"id"`
	EnmasseUserID *uuid.UUID `json:"enmasse_user_id"`
}

func (q *Queries) SetMakerEnmasseUserID(ctx context.Context, arg SetMakerEnmasseUserIDParams) error {
	_, err := q.db.Exec(ctx, setMakerEnmasseUserID, arg.ID, arg.EnmasseUserID)
	return err
}

const setPublication = `-- name: SetPublication :exec
UPDATE makers
SET publication_status = $2, updated_at = NOW()
WHERE id = $1
`

type SetPublicationParams struct {
	ID                uuid.UUID         `json:"id"`
	PublicationStatus PublicationStatus `json:"publication_status"`
}

func (q *Queries) SetPublication(ctx context.Context, arg SetPublicationParams) error {
	_, err := q.db.Exec(ctx, setPublication, arg.ID, arg.PublicationStatus)
	return err
}

const upsertContact = `-- name: UpsertContact :one
INSERT INTO maker_contacts (maker_id, channel, e164_digits, publish_permitted)
VALUES ($1, $2, $3, FALSE)
ON CONFLICT (maker_id) DO UPDATE
SET channel = EXCLUDED.channel, e164_digits = EXCLUDED.e164_digits
RETURNING id, maker_id, channel, e164_digits, publish_permitted, permission_at
`

type UpsertContactParams struct {
	MakerID    uuid.UUID `json:"maker_id"`
	Channel    string    `json:"channel"`
	E164Digits string    `json:"e164_digits"`
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) (MakerContact, error) {
	row := q.db.QueryRow(ctx, upsertContact, arg.MakerID, arg.Channel, arg.E164Digits)
	var i MakerContact
	err := row.Scan(
		&i.ID,
		&i.MakerID,
		&i.Channel,
		&i.E164Digits,
		&i.PublishPermitted,
		&i.PermissionAt,
	)
	return i, err
}
