// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalogue.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPublishedMakers = `-- name: CountPublishedMakers :one
SELECT count(*)::bigint
FROM makers
WHERE publication_status = 'published'
  AND is_demo_fixture = FALSE
`

func (q *Queries) CountPublishedMakers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedMakers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteMakerMedia = `-- name: DeleteMakerMedia :exec
DELETE FROM maker_media WHERE maker_id = $1
`

func (q *Queries) DeleteMakerMedia(ctx context.Context, makerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMakerMedia, makerID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT slug, label_id, shortcut_order, group_slug, publication_status, source, proposed_by_maker_id
FROM categories
WHERE slug = $1
`

func (q *Queries) GetCategory(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, slug)
	var i Category
	err := row.Scan(
		&i.Slug,
		&i.LabelID,
		&i.ShortcutOrder,
		&i.GroupSlug,
		&i.PublicationStatus,
		&i.Source,
		&i.ProposedByMakerID,
	)
	return i, err
}

const getCategoryByLabel = `-- name: GetCategoryByLabel :one
SELECT slug, label_id
FROM categories
WHERE lower(label_id) = lower($1)
`

type GetCategoryByLabelRow struct {
	Slug    string `json:"slug"`
	LabelID string `json:"label_id"`
}

func (q *Queries) GetCategoryByLabel(ctx context.Context, lower string) (GetCategoryByLabelRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByLabel, lower)
	var i GetCategoryByLabelRow
	err := row.Scan(&i.Slug, &i.LabelID)
	return i, err
}

const getCategoryGroup = `-- name: GetCategoryGroup :one
SELECT slug, label_id, shortcut_order, publication_status, source, proposed_by_maker_id
FROM category_groups
WHERE slug = $1
`

type GetCategoryGroupRow struct {
	Slug              string            `json:"slug"`
	LabelID           string            `json:"label_id"`
	ShortcutOrder     int32             `json:"shortcut_order"`
	PublicationStatus PublicationStatus `json:"publication_status"`
	Source            string            `json:"source"`
	ProposedByMakerID *uuid.UUID        `json:"proposed_by_maker_id"`
}

func (q *Queries) GetCategoryGroup(ctx context.Context, slug string) (GetCategoryGroupRow, error) {
	row := q.db.QueryRow(ctx, getCategoryGroup, slug)
	var i GetCategoryGroupRow
	err := row.Scan(
		&i.Slug,
		&i.LabelID,
		&i.ShortcutOrder,
		&i.PublicationStatus,
		&i.Source,
		&i.ProposedByMakerID,
	)
	return i, err
}

const getCategoryGroupByLabel = `-- name: GetCategoryGroupByLabel :one
SELECT slug, label_id
FROM category_groups
WHERE lower(label_id) = lower($1)
`

type GetCategoryGroupByLabelRow struct {
	Slug    string `json:"slug"`
	LabelID string `json:"label_id"`
}

func (q *Queries) GetCategoryGroupByLabel(ctx context.Context, lower string) (GetCategoryGroupByLabelRow, error) {
	row := q.db.QueryRow(ctx, getCategoryGroupByLabel, lower)
	var i GetCategoryGroupByLabelRow
	err := row.Scan(&i.Slug, &i.LabelID)
	return i, err
}

const getMaker = `-- name: GetMaker :one
SELECT
    m.id,
    m.name,
    m.city,
    m.publication_status,
    m.verification_date,
    m.moq_quantity,
    m.moq_basis,
    m.moq_basis_note,
    m.lead_time_estimate,
    m.price_min_idr,
    m.price_max_idr,
    m.price_note,
    m.conditions,
    m.is_demo_fixture,
    m.enmasse_vendor_id,
    m.enmasse_user_id,
    m.hours_open,
    m.hours_close,
    m.hours_days,
    m.service_area
FROM makers m
WHERE m.id = $1
`

type GetMakerRow struct {
	ID                uuid.UUID         `json:"id"`
	Name              string            `json:"name"`
	City              string            `json:"city"`
	PublicationStatus PublicationStatus `json:"publication_status"`
	VerificationDate  *time.Time        `json:"verification_date"`
	MoqQuantity       *int32            `json:"moq_quantity"`
	MoqBasis          NullMoqBasis      `json:"moq_basis"`
	MoqBasisNote      *string           `json:"moq_basis_note"`
	LeadTimeEstimate  *string           `json:"lead_time_estimate"`
	PriceMinIdr       *int32            `json:"price_min_idr"`
	PriceMaxIdr       *int32            `json:"price_max_idr"`
	PriceNote         *string           `json:"price_note"`
	Conditions        *string           `json:"conditions"`
	IsDemoFixture     bool              `json:"is_demo_fixture"`
	EnmasseVendorID   *uuid.UUID        `json:"enmasse_vendor_id"`
	EnmasseUserID     *uuid.UUID        `json:"enmasse_user_id"`
	HoursOpen         *string           `json:"hours_open"`
	HoursClose        *string           `json:"hours_close"`
	HoursDays         []string          `json:"hours_days"`
	ServiceArea       *string           `json:"service_area"`
}

func (q *Queries) GetMaker(ctx context.Context, id uuid.UUID) (GetMakerRow, error) {
	row := q.db.QueryRow(ctx, getMaker, id)
	var i GetMakerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.PublicationStatus,
		&i.VerificationDate,
		&i.MoqQuantity,
		&i.MoqBasis,
		&i.MoqBasisNote,
		&i.LeadTimeEstimate,
		&i.PriceMinIdr,
		&i.PriceMaxIdr,
		&i.PriceNote,
		&i.Conditions,
		&i.IsDemoFixture,
		&i.EnmasseVendorID,
		&i.EnmasseUserID,
		&i.HoursOpen,
		&i.HoursClose,
		&i.HoursDays,
		&i.ServiceArea,
	)
	return i, err
}

const getMakerByEnmasseVendor = `-- name: GetMakerByEnmasseVendor :one
SELECT
    m.id,
    m.name,
    m.city,
    m.publication_status,
    m.verification_date,
    m.moq_quantity,
    m.moq_basis,
    m.moq_basis_note,
    m.lead_time_estimate,
    m.price_min_idr,
    m.price_max_idr,
    m.price_note,
    m.conditions,
    m.is_demo_fixture,
    m.enmasse_vendor_id,
    m.enmasse_user_id,
    m.hours_open,
    m.hours_close,
    m.hours_days,
    m.service_area
FROM makers m
WHERE m.enmasse_vendor_id = $1
`

type GetMakerByEnmasseVendorRow struct {
	ID                uuid.UUID         `json:"id"`
	Name              string            `json:"name"`
	City              string            `json:"city"`
	PublicationStatus PublicationStatus `json:"publication_status"`
	VerificationDate  *time.Time        `json:"verification_date"`
	MoqQuantity       *int32            `json:"moq_quantity"`
	MoqBasis          NullMoqBasis      `json:"moq_basis"`
	MoqBasisNote      *string           `json:"moq_basis_note"`
	LeadTimeEstimate  *string           `json:"lead_time_estimate"`
	PriceMinIdr       *int32            `json:"price_min_idr"`
	PriceMaxIdr       *int32            `json:"price_max_idr"`
	PriceNote         *string           `json:"price_note"`
	Conditions        *string           `json:"conditions"`
	IsDemoFixture     bool              `json:"is_demo_fixture"`
	EnmasseVendorID   *uuid.UUID        `json:"enmasse_vendor_id"`
	EnmasseUserID     *uuid.UUID        `json:"enmasse_user_id"`
	HoursOpen         *string           `json:"hours_open"`
	HoursClose        *string           `json:"hours_close"`
	HoursDays         []string          `json:"hours_days"`
	ServiceArea       *string           `json:"service_area"`
}

func (q *Queries) GetMakerByEnmasseVendor(ctx context.Context, enmasseVendorID *uuid.UUID) (GetMakerByEnmasseVendorRow, error) {
	row := q.db.QueryRow(ctx, getMakerByEnmasseVendor, enmasseVendorID)
	var i GetMakerByEnmasseVendorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.PublicationStatus,
		&i.VerificationDate,
		&i.MoqQuantity,
		&i.MoqBasis,
		&i.MoqBasisNote,
		&i.LeadTimeEstimate,
		&i.PriceMinIdr,
		&i.PriceMaxIdr,
		&i.PriceNote,
		&i.Conditions,
		&i.IsDemoFixture,
		&i.EnmasseVendorID,
		&i.EnmasseUserID,
		&i.HoursOpen,
		&i.HoursClose,
		&i.HoursDays,
		&i.ServiceArea,
	)
	return i, err
}

const getMakerContact = `-- name: GetMakerContact :one
SELECT id, maker_id, channel, e164_digits, publish_permitted, permission_at
FROM maker_contacts
WHERE maker_id = $1
`

func (q *Queries) GetMakerContact(ctx context.Context, makerID uuid.UUID) (MakerContact, error) {
	row := q.db.QueryRow(ctx, getMakerContact, makerID)
	var i MakerContact
	err := row.Scan(
		&i.ID,
		&i.MakerID,
		&i.Channel,
		&i.E164Digits,
		&i.PublishPermitted,
		&i.PermissionAt,
	)
	return i, err
}

const getSynonym = `-- name: GetSynonym :one
SELECT category_slug, synonym
FROM category_synonyms
WHERE synonym = $1
`

type GetSynonymRow struct {
	CategorySlug string `json:"category_slug"`
	Synonym      string `json:"synonym"`
}

func (q *Queries) GetSynonym(ctx context.Context, synonym string) (GetSynonymRow, error) {
	row := q.db.QueryRow(ctx, getSynonym, synonym)
	var i GetSynonymRow
	err := row.Scan(&i.CategorySlug, &i.Synonym)
	return i, err
}

const insertCategoryGroup = `-- name: InsertCategoryGroup :one
INSERT INTO category_groups (slug, label_id, shortcut_order, publication_status, source, proposed_by_maker_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING slug, label_id, shortcut_order, publication_status, source, proposed_by_maker_id, created_at
`

type InsertCategoryGroupParams struct {
	Slug              string            `json:"slug"`
	LabelID           string            `json:"label_id"`
	ShortcutOrder     int32             `json:"shortcut_order"`
	PublicationStatus PublicationStatus `json:"publication_status"`
	Source            string            `json:"source"`
	ProposedByMakerID *uuid.UUID        `json:"proposed_by_maker_id"`
}

func (q *Queries) InsertCategoryGroup(ctx context.Context, arg InsertCategoryGroupParams) (CategoryGroup, error) {
	row := q.db.QueryRow(ctx, insertCategoryGroup,
		arg.Slug,
		arg.LabelID,
		arg.ShortcutOrder,
		arg.PublicationStatus,
		arg.Source,
		arg.ProposedByMakerID,
	)
	var i CategoryGroup
	err := row.Scan(
		&i.Slug,
		&i.LabelID,
		&i.ShortcutOrder,
		&i.PublicationStatus,
		&i.Source,
		&i.ProposedByMakerID,
		&i.CreatedAt,
	)
	return i, err
}

const insertCategoryRow = `-- name: InsertCategoryRow :one
INSERT INTO categories (slug, label_id, shortcut_order, group_slug, publication_status, source, proposed_by_maker_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING slug, label_id, shortcut_order, group_slug, publication_status, source, proposed_by_maker_id
`

type InsertCategoryRowParams struct {
	Slug              string            `json:"slug"`
	LabelID           string            `json:"label_id"`
	ShortcutOrder     int32             `json:"shortcut_order"`
	GroupSlug         string            `json:"group_slug"`
	PublicationStatus PublicationStatus `json:"publication_status"`
	Source            string            `json:"source"`
	ProposedByMakerID *uuid.UUID        `json:"proposed_by_maker_id"`
}

func (q *Queries) InsertCategoryRow(ctx context.Context, arg InsertCategoryRowParams) (Category, error) {
	row := q.db.QueryRow(ctx, insertCategoryRow,
		arg.Slug,
		arg.LabelID,
		arg.ShortcutOrder,
		arg.GroupSlug,
		arg.PublicationStatus,
		arg.Source,
		arg.ProposedByMakerID,
	)
	var i Category
	err := row.Scan(
		&i.Slug,
		&i.LabelID,
		&i.ShortcutOrder,
		&i.GroupSlug,
		&i.PublicationStatus,
		&i.Source,
		&i.ProposedByMakerID,
	)
	return i, err
}

const insertMakerMedia = `-- name: InsertMakerMedia :exec
INSERT INTO maker_media (maker_id, url, alt, sort_order)
VALUES ($1, $2, $3, $4)
`

type InsertMakerMediaParams struct {
	MakerID   uuid.UUID `json:"maker_id"`
	Url       string    `json:"url"`
	Alt       string    `json:"alt"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) InsertMakerMedia(ctx context.Context, arg InsertMakerMediaParams) error {
	_, err := q.db.Exec(ctx, insertMakerMedia,
		arg.MakerID,
		arg.Url,
		arg.Alt,
		arg.SortOrder,
	)
	return err
}

const insertSynonym = `-- name: InsertSynonym :exec
INSERT INTO category_synonyms (category_slug, synonym)
VALUES ($1, $2)
ON CONFLICT (synonym) DO NOTHING
`

type InsertSynonymParams struct {
	CategorySlug string `json:"category_slug"`
	Synonym      string `json:"synonym"`
}

func (q *Queries) InsertSynonym(ctx context.Context, arg InsertSynonymParams) error {
	_, err := q.db.Exec(ctx, insertSynonym, arg.CategorySlug, arg.Synonym)
	return err
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT slug, label_id, shortcut_order, group_slug, publication_status, source, proposed_by_maker_id
FROM categories
ORDER BY shortcut_order, slug
`

func (q *Queries) ListAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.Slug,
			&i.LabelID,
			&i.ShortcutOrder,
			&i.GroupSlug,
			&i.PublicationStatus,
			&i.Source,
			&i.ProposedByMakerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT slug, label_id, shortcut_order, group_slug
FROM categories
WHERE publication_status = 'published'
ORDER BY shortcut_order, slug
`

type ListCategoriesRow struct {
	Slug          string `json:"slug"`
	LabelID       string `json:"label_id"`
	ShortcutOrder int32  `json:"shortcut_order"`
	GroupSlug     string `json:"group_slug"`
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.Slug,
			&i.LabelID,
			&i.ShortcutOrder,
			&i.GroupSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryGroups = `-- name: ListCategoryGroups :many
SELECT slug, label_id, shortcut_order
FROM category_groups
WHERE publication_status = 'published'
ORDER BY shortcut_order, slug
`

type ListCategoryGroupsRow struct {
	Slug          string `json:"slug"`
	LabelID       string `json:"label_id"`
	ShortcutOrder int32  `json:"shortcut_order"`
}

func (q *Queries) ListCategoryGroups(ctx context.Context) ([]ListCategoryGroupsRow, error) {
	rows, err := q.db.Query(ctx, listCategoryGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoryGroupsRow{}
	for rows.Next() {
		var i ListCategoryGroupsRow
		if err := rows.Scan(&i.Slug, &i.LabelID, &i.ShortcutOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftCategories = `-- name: ListDraftCategories :many
SELECT slug, label_id, shortcut_order, group_slug, publication_status, source, proposed_by_maker_id
FROM categories
WHERE publication_status = 'draft'
ORDER BY slug
`

func (q *Queries) ListDraftCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listDraftCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.Slug,
			&i.LabelID,
			&i.ShortcutOrder,
			&i.GroupSlug,
			&i.PublicationStatus,
			&i.Source,
			&i.ProposedByMakerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftCategoryGroups = `-- name: ListDraftCategoryGroups :many
SELECT slug, label_id, shortcut_order, publication_status, source, proposed_by_maker_id, created_at
FROM category_groups
WHERE publication_status = 'draft'
ORDER BY created_at DESC
`

func (q *Queries) ListDraftCategoryGroups(ctx context.Context) ([]CategoryGroup, error) {
	rows, err := q.db.Query(ctx, listDraftCategoryGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryGroup{}
	for rows.Next() {
		var i CategoryGroup
		if err := rows.Scan(
			&i.Slug,
			&i.LabelID,
			&i.ShortcutOrder,
			&i.PublicationStatus,
			&i.Source,
			&i.ProposedByMakerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMakerCapabilities = `-- name: ListMakerCapabilities :many
SELECT mc.maker_id, mc.category_slug, cat.label_id, cat.publication_status
FROM maker_capabilities mc
JOIN categories cat ON cat.slug = mc.category_slug
WHERE mc.maker_id = ANY ($1::uuid[])
`

type ListMakerCapabilitiesRow struct {
	MakerID           uuid.UUID         `json:"maker_id"`
	CategorySlug      string            `json:"category_slug"`
	LabelID           string            `json:"label_id"`
	PublicationStatus PublicationStatus `json:"publication_status"`
}

func (q *Queries) ListMakerCapabilities(ctx context.Context, makerIds []uuid.UUID) ([]ListMakerCapabilitiesRow, error) {
	rows, err := q.db.Query(ctx, listMakerCapabilities, makerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMakerCapabilitiesRow{}
	for rows.Next() {
		var i ListMakerCapabilitiesRow
		if err := rows.Scan(
			&i.MakerID,
			&i.CategorySlug,
			&i.LabelID,
			&i.PublicationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMakerDraftCategories = `-- name: ListMakerDraftCategories :many
SELECT slug, label_id, shortcut_order, group_slug, publication_status
FROM categories
WHERE proposed_by_maker_id = $1
ORDER BY slug
`

type ListMakerDraftCategoriesRow struct {
	Slug              string            `json:"slug"`
	LabelID           string            `json:"label_id"`
	ShortcutOrder     int32             `json:"shortcut_order"`
	GroupSlug         string            `json:"group_slug"`
	PublicationStatus PublicationStatus `json:"publication_status"`
}

func (q *Queries) ListMakerDraftCategories(ctx context.Context, proposedByMakerID *uuid.UUID) ([]ListMakerDraftCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listMakerDraftCategories, proposedByMakerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMakerDraftCategoriesRow{}
	for rows.Next() {
		var i ListMakerDraftCategoriesRow
		if err := rows.Scan(
			&i.Slug,
			&i.LabelID,
			&i.ShortcutOrder,
			&i.GroupSlug,
			&i.PublicationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMakerDraftCategoryGroups = `-- name: ListMakerDraftCategoryGroups :many
SELECT slug, label_id, shortcut_order, publication_status
FROM category_groups
WHERE proposed_by_maker_id = $1
ORDER BY slug
`

type ListMakerDraftCategoryGroupsRow struct {
	Slug              string            `json:"slug"`
	LabelID           string            `json:"label_id"`
	ShortcutOrder     int32             `json:"shortcut_order"`
	PublicationStatus PublicationStatus `json:"publication_status"`
}

func (q *Queries) ListMakerDraftCategoryGroups(ctx context.Context, proposedByMakerID *uuid.UUID) ([]ListMakerDraftCategoryGroupsRow, error) {
	rows, err := q.db.Query(ctx, listMakerDraftCategoryGroups, proposedByMakerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMakerDraftCategoryGroupsRow{}
	for rows.Next() {
		var i ListMakerDraftCategoryGroupsRow
		if err := rows.Scan(
			&i.Slug,
			&i.LabelID,
			&i.ShortcutOrder,
			&i.PublicationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMakerMedia = `-- name: ListMakerMedia :many
SELECT id, maker_id, url, alt, sort_order
FROM maker_media
WHERE maker_id = $1
ORDER BY sort_order, id
`

func (q *Queries) ListMakerMedia(ctx context.Context, makerID uuid.UUID) ([]MakerMedium, error) {
	rows, err := q.db.Query(ctx, listMakerMedia, makerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MakerMedium{}
	for rows.Next() {
		var i MakerMedium
		if err := rows.Scan(
			&i.ID,
			&i.MakerID,
			&i.Url,
			&i.Alt,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedMakers = `-- name: ListPublishedMakers :many
SELECT
    m.id,
    m.name,
    m.city,
    m.verification_date,
    m.moq_quantity,
    m.moq_basis,
    m.moq_basis_note,
    m.lead_time_estimate,
    m.price_min_idr,
    m.price_max_idr,
    m.price_note
FROM makers m
WHERE m.publication_status = 'published'
  AND m.is_demo_fixture = FALSE
  AND (
      $1::text IS NULL
      OR EXISTS (
          SELECT 1 FROM maker_capabilities c
          WHERE c.maker_id = m.id AND c.category_slug = $1
      )
  )
ORDER BY m.name
`

type ListPublishedMakersRow struct {
	ID               uuid.UUID    `json:"id"`
	Name             string       `json:"name"`
	City             string       `json:"city"`
	VerificationDate *time.Time   `json:"verification_date"`
	MoqQuantity      *int32       `json:"moq_quantity"`
	MoqBasis         NullMoqBasis `json:"moq_basis"`
	MoqBasisNote     *string      `json:"moq_basis_note"`
	LeadTimeEstimate *string      `json:"lead_time_estimate"`
	PriceMinIdr      *int32       `json:"price_min_idr"`
	PriceMaxIdr      *int32       `json:"price_max_idr"`
	PriceNote        *string      `json:"price_note"`
}

func (q *Queries) ListPublishedMakers(ctx context.Context, category *string) ([]ListPublishedMakersRow, error) {
	rows, err := q.db.Query(ctx, listPublishedMakers, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedMakersRow{}
	for rows.Next() {
		var i ListPublishedMakersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.VerificationDate,
			&i.MoqQuantity,
			&i.MoqBasis,
			&i.MoqBasisNote,
			&i.LeadTimeEstimate,
			&i.PriceMinIdr,
			&i.PriceMaxIdr,
			&i.PriceNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedRecommendations = `-- name: ListPublishedRecommendations :many
SELECT
    r.id,
    r.product_made,
    r.production_date_approx,
    r.body,
    r.quantity,
    r.would_use_again,
    a.display_name
FROM recommendations r
JOIN artists a ON a.id = r.artist_id
WHERE r.maker_id = $1
  AND r.publication_status = 'published'
ORDER BY r.created_at DESC
`

type ListPublishedRecommendationsRow struct {
	ID                   uuid.UUID `json:"id"`
	ProductMade          string    `json:"product_made"`
	ProductionDateApprox string    `json:"production_date_approx"`
	Body                 string    `json:"body"`
	Quantity             *string   `json:"quantity"`
	WouldUseAgain        *bool     `json:"would_use_again"`
	DisplayName          string    `json:"display_name"`
}

func (q *Queries) ListPublishedRecommendations(ctx context.Context, makerID uuid.UUID) ([]ListPublishedRecommendationsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedRecommendations, makerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedRecommendationsRow{}
	for rows.Next() {
		var i ListPublishedRecommendationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductMade,
			&i.ProductionDateApprox,
			&i.Body,
			&i.Quantity,
			&i.WouldUseAgain,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCategoryGroupPublication = `-- name: SetCategoryGroupPublication :exec
UPDATE category_groups
SET publication_status = $2
WHERE slug = $1
`

type SetCategoryGroupPublicationParams struct {
	Slug              string            `json:"slug"`
	PublicationStatus PublicationStatus `json:"publication_status"`
}

func (q *Queries) SetCategoryGroupPublication(ctx context.Context, arg SetCategoryGroupPublicationParams) error {
	_, err := q.db.Exec(ctx, setCategoryGroupPublication, arg.Slug, arg.PublicationStatus)
	return err
}

const setCategoryPublication = `-- name: SetCategoryPublication :exec
UPDATE categories
SET publication_status = $2
WHERE slug = $1
`

type SetCategoryPublicationParams struct {
	Slug              string            `json:"slug"`
	PublicationStatus PublicationStatus `json:"publication_status"`
}

func (q *Queries) SetCategoryPublication(ctx context.Context, arg SetCategoryPublicationParams) error {
	_, err := q.db.Exec(ctx, setCategoryPublication, arg.Slug, arg.PublicationStatus)
	return err
}

const updateMakerIdentity = `-- name: UpdateMakerIdentity :exec
UPDATE makers
SET name = $2,
    city = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateMakerIdentityParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	City string    `json:"city"`
}

func (q *Queries) UpdateMakerIdentity(ctx context.Context, arg UpdateMakerIdentityParams) error {
	_, err := q.db.Exec(ctx, updateMakerIdentity, arg.ID, arg.Name, arg.City)
	return err
}

const updateMakerOverlay = `-- name: UpdateMakerOverlay :exec
UPDATE makers
SET hours_open = $2,
    hours_close = $3,
    hours_days = $4,
    price_min_idr = $5,
    price_max_idr = $6,
    price_note = $7,
    moq_quantity = $8,
    moq_basis = $9,
    moq_basis_note = $10,
    lead_time_estimate = $11,
    updated_at = NOW()
WHERE id = $1
`

type UpdateMakerOverlayParams struct {
	ID               uuid.UUID    `json:"id"`
	HoursOpen        *string      `json:"hours_open"`
	HoursClose       *string      `json:"hours_close"`
	HoursDays        []string     `json:"hours_days"`
	PriceMinIdr      *int32       `json:"price_min_idr"`
	PriceMaxIdr      *int32       `json:"price_max_idr"`
	PriceNote        *string      `json:"price_note"`
	MoqQuantity      *int32       `json:"moq_quantity"`
	MoqBasis         NullMoqBasis `json:"moq_basis"`
	MoqBasisNote     *string      `json:"moq_basis_note"`
	LeadTimeEstimate *string      `json:"lead_time_estimate"`
}

func (q *Queries) UpdateMakerOverlay(ctx context.Context, arg UpdateMakerOverlayParams) error {
	_, err := q.db.Exec(ctx, updateMakerOverlay,
		arg.ID,
		arg.HoursOpen,
		arg.HoursClose,
		arg.HoursDays,
		arg.PriceMinIdr,
		arg.PriceMaxIdr,
		arg.PriceNote,
		arg.MoqQuantity,
		arg.MoqBasis,
		arg.MoqBasisNote,
		arg.LeadTimeEstimate,
	)
	return err
}
