// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consents.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activityTrackingGranted = `-- name: ActivityTrackingGranted :one
SELECT EXISTS (
    SELECT 1
    FROM consents
    WHERE consent_type = 'activity_tracking'
      AND granted = TRUE
      AND withdrawn_at IS NULL
      AND (
          anon_session_id = $1
          OR ($2::uuid IS NOT NULL AND user_id = $2)
      )
)::bool AS granted
`

type ActivityTrackingGrantedParams struct {
	AnonSessionID uuid.UUID  `json:"anon_session_id"`
	UserID        *uuid.UUID `json:"user_id"`
}

func (q *Queries) ActivityTrackingGranted(ctx context.Context, arg ActivityTrackingGrantedParams) (bool, error) {
	row := q.db.QueryRow(ctx, activityTrackingGranted, arg.AnonSessionID, arg.UserID)
	var granted bool
	err := row.Scan(&granted)
	return granted, err
}

const backfillConsentUser = `-- name: BackfillConsentUser :exec
UPDATE consents
SET user_id = $2, updated_at = NOW()
WHERE consents.anon_session_id = $1
  AND consents.user_id IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM consents other
      WHERE other.user_id = $2
        AND other.consent_type = consents.consent_type
  )
`

type BackfillConsentUserParams struct {
	AnonSessionID uuid.UUID  `json:"anon_session_id"`
	UserID        *uuid.UUID `json:"user_id"`
}

func (q *Queries) BackfillConsentUser(ctx context.Context, arg BackfillConsentUserParams) error {
	_, err := q.db.Exec(ctx, backfillConsentUser, arg.AnonSessionID, arg.UserID)
	return err
}

const getConsentBySessionType = `-- name: GetConsentBySessionType :one
SELECT id, user_id, anon_session_id, consent_type, version, granted, granted_at, withdrawn_at, source, ip_hash, user_agent_hash, created_at, updated_at
FROM consents
WHERE anon_session_id = $1
  AND consent_type = $2
`

type GetConsentBySessionTypeParams struct {
	AnonSessionID uuid.UUID   `json:"anon_session_id"`
	ConsentType   ConsentType `json:"consent_type"`
}

func (q *Queries) GetConsentBySessionType(ctx context.Context, arg GetConsentBySessionTypeParams) (Consent, error) {
	row := q.db.QueryRow(ctx, getConsentBySessionType, arg.AnonSessionID, arg.ConsentType)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonSessionID,
		&i.ConsentType,
		&i.Version,
		&i.Granted,
		&i.GrantedAt,
		&i.WithdrawnAt,
		&i.Source,
		&i.IpHash,
		&i.UserAgentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConsentByUserType = `-- name: GetConsentByUserType :one
SELECT id, user_id, anon_session_id, consent_type, version, granted, granted_at, withdrawn_at, source, ip_hash, user_agent_hash, created_at, updated_at
FROM consents
WHERE user_id = $1
  AND consent_type = $2
`

type GetConsentByUserTypeParams struct {
	UserID      *uuid.UUID  `json:"user_id"`
	ConsentType ConsentType `json:"consent_type"`
}

func (q *Queries) GetConsentByUserType(ctx context.Context, arg GetConsentByUserTypeParams) (Consent, error) {
	row := q.db.QueryRow(ctx, getConsentByUserType, arg.UserID, arg.ConsentType)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonSessionID,
		&i.ConsentType,
		&i.Version,
		&i.Granted,
		&i.GrantedAt,
		&i.WithdrawnAt,
		&i.Source,
		&i.IpHash,
		&i.UserAgentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConsent = `-- name: InsertConsent :one
INSERT INTO consents (
    user_id, anon_session_id, consent_type, version, granted,
    granted_at, withdrawn_at, source, ip_hash, user_agent_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, anon_session_id, consent_type, version, granted, granted_at, withdrawn_at, source, ip_hash, user_agent_hash, created_at, updated_at
`

type InsertConsentParams struct {
	UserID        *uuid.UUID         `json:"user_id"`
	AnonSessionID uuid.UUID          `json:"anon_session_id"`
	ConsentType   ConsentType        `json:"consent_type"`
	Version       string             `json:"version"`
	Granted       bool               `json:"granted"`
	GrantedAt     pgtype.Timestamptz `json:"granted_at"`
	WithdrawnAt   pgtype.Timestamptz `json:"withdrawn_at"`
	Source        ConsentSource      `json:"source"`
	IpHash        string             `json:"ip_hash"`
	UserAgentHash string             `json:"user_agent_hash"`
}

func (q *Queries) InsertConsent(ctx context.Context, arg InsertConsentParams) (Consent, error) {
	row := q.db.QueryRow(ctx, insertConsent,
		arg.UserID,
		arg.AnonSessionID,
		arg.ConsentType,
		arg.Version,
		arg.Granted,
		arg.GrantedAt,
		arg.WithdrawnAt,
		arg.Source,
		arg.IpHash,
		arg.UserAgentHash,
	)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonSessionID,
		&i.ConsentType,
		&i.Version,
		&i.Granted,
		&i.GrantedAt,
		&i.WithdrawnAt,
		&i.Source,
		&i.IpHash,
		&i.UserAgentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConsentsByUser = `-- name: ListConsentsByUser :many
SELECT id, user_id, anon_session_id, consent_type, version, granted, granted_at, withdrawn_at, source, ip_hash, user_agent_hash, created_at, updated_at
FROM consents
WHERE user_id = $1
ORDER BY consent_type
`

func (q *Queries) ListConsentsByUser(ctx context.Context, userID *uuid.UUID) ([]Consent, error) {
	rows, err := q.db.Query(ctx, listConsentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Consent{}
	for rows.Next() {
		var i Consent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AnonSessionID,
			&i.ConsentType,
			&i.Version,
			&i.Granted,
			&i.GrantedAt,
			&i.WithdrawnAt,
			&i.Source,
			&i.IpHash,
			&i.UserAgentHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConsent = `-- name: UpdateConsent :one
UPDATE consents
SET
    user_id = COALESCE($2, user_id),
    anon_session_id = $3,
    version = $4,
    granted = $5,
    granted_at = $6,
    withdrawn_at = $7,
    source = $8,
    ip_hash = $9,
    user_agent_hash = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, anon_session_id, consent_type, version, granted, granted_at, withdrawn_at, source, ip_hash, user_agent_hash, created_at, updated_at
`

type UpdateConsentParams struct {
	ID            uuid.UUID          `json:"id"`
	UserID        *uuid.UUID         `json:"user_id"`
	AnonSessionID uuid.UUID          `json:"anon_session_id"`
	Version       string             `json:"version"`
	Granted       bool               `json:"granted"`
	GrantedAt     pgtype.Timestamptz `json:"granted_at"`
	WithdrawnAt   pgtype.Timestamptz `json:"withdrawn_at"`
	Source        ConsentSource      `json:"source"`
	IpHash        string             `json:"ip_hash"`
	UserAgentHash string             `json:"user_agent_hash"`
}

func (q *Queries) UpdateConsent(ctx context.Context, arg UpdateConsentParams) (Consent, error) {
	row := q.db.QueryRow(ctx, updateConsent,
		arg.ID,
		arg.UserID,
		arg.AnonSessionID,
		arg.Version,
		arg.Granted,
		arg.GrantedAt,
		arg.WithdrawnAt,
		arg.Source,
		arg.IpHash,
		arg.UserAgentHash,
	)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonSessionID,
		&i.ConsentType,
		&i.Version,
		&i.Granted,
		&i.GrantedAt,
		&i.WithdrawnAt,
		&i.Source,
		&i.IpHash,
		&i.UserAgentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const whatsAppPublicationGrantedForMaker = `-- name: WhatsAppPublicationGrantedForMaker :one
SELECT EXISTS (
    SELECT 1
    FROM consents c
    JOIN makers m ON m.enmasse_user_id = c.user_id
    WHERE m.id = $1
      AND c.consent_type = 'whatsapp_publication'
      AND c.granted = TRUE
      AND c.withdrawn_at IS NULL
)::bool AS granted
`

func (q *Queries) WhatsAppPublicationGrantedForMaker(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, whatsAppPublicationGrantedForMaker, id)
	var granted bool
	err := row.Scan(&granted)
	return granted, err
}
