// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const backfillSessionUser = `-- name: BackfillSessionUser :exec
UPDATE events
SET enmasse_user_id = $2
WHERE anon_session_id = $1
  AND enmasse_user_id IS NULL
`

type BackfillSessionUserParams struct {
	AnonSessionID uuid.UUID  `json:"anon_session_id"`
	EnmasseUserID *uuid.UUID `json:"enmasse_user_id"`
}

func (q *Queries) BackfillSessionUser(ctx context.Context, arg BackfillSessionUserParams) error {
	_, err := q.db.Exec(ctx, backfillSessionUser, arg.AnonSessionID, arg.EnmasseUserID)
	return err
}

const countRecentContactClicks = `-- name: CountRecentContactClicks :one
SELECT COUNT(*)::int AS n
FROM events
WHERE type = 'contact_click'
  AND counted = TRUE
  AND anon_session_id = $1
  AND maker_id = $2
  AND created_at >= $3
`

type CountRecentContactClicksParams struct {
	AnonSessionID uuid.UUID  `json:"anon_session_id"`
	MakerID       *uuid.UUID `json:"maker_id"`
	CreatedAt     time.Time  `json:"created_at"`
}

func (q *Queries) CountRecentContactClicks(ctx context.Context, arg CountRecentContactClicksParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentContactClicks, arg.AnonSessionID, arg.MakerID, arg.CreatedAt)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
    type, traffic_source, anon_session_id, enmasse_user_id, raw_query, interpreted_category,
    matched_synonym, result_count, no_result_reason, maker_id, counted
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, type, traffic_source, anon_session_id, raw_query, interpreted_category, matched_synonym, result_count, no_result_reason, maker_id, counted, created_at, enmasse_user_id
`

type InsertEventParams struct {
	Type                EventType     `json:"type"`
	TrafficSource       TrafficSource `json:"traffic_source"`
	AnonSessionID       uuid.UUID     `json:"anon_session_id"`
	EnmasseUserID       *uuid.UUID    `json:"enmasse_user_id"`
	RawQuery            *string       `json:"raw_query"`
	InterpretedCategory *string       `json:"interpreted_category"`
	MatchedSynonym      *string       `json:"matched_synonym"`
	ResultCount         *int32        `json:"result_count"`
	NoResultReason      *string       `json:"no_result_reason"`
	MakerID             *uuid.UUID    `json:"maker_id"`
	Counted             bool          `json:"counted"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.Type,
		arg.TrafficSource,
		arg.AnonSessionID,
		arg.EnmasseUserID,
		arg.RawQuery,
		arg.InterpretedCategory,
		arg.MatchedSynonym,
		arg.ResultCount,
		arg.NoResultReason,
		arg.MakerID,
		arg.Counted,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TrafficSource,
		&i.AnonSessionID,
		&i.RawQuery,
		&i.InterpretedCategory,
		&i.MatchedSynonym,
		&i.ResultCount,
		&i.NoResultReason,
		&i.MakerID,
		&i.Counted,
		&i.CreatedAt,
		&i.EnmasseUserID,
	)
	return i, err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (anon_session_id, enmasse_user_id, last_flush_at)
VALUES ($1, $2, NOW())
ON CONFLICT (anon_session_id) DO UPDATE SET
    last_flush_at = NOW(),
    enmasse_user_id = COALESCE(sessions.enmasse_user_id, EXCLUDED.enmasse_user_id)
`

type UpsertSessionParams struct {
	AnonSessionID uuid.UUID  `json:"anon_session_id"`
	EnmasseUserID *uuid.UUID `json:"enmasse_user_id"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.Exec(ctx, upsertSession, arg.AnonSessionID, arg.EnmasseUserID)
	return err
}
