// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ConsentSource string

const (
	ConsentSourceSignup         ConsentSource = "signup"
	ConsentSourceOnboarding     ConsentSource = "onboarding"
	ConsentSourceActivityBanner ConsentSource = "activity_banner"
	ConsentSourceFooter         ConsentSource = "footer"
)

func (e *ConsentSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsentSource(s)
	case string:
		*e = ConsentSource(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsentSource: %T", src)
	}
	return nil
}

type NullConsentSource struct {
	ConsentSource ConsentSource `json:"consent_source"`
	Valid         bool          `json:"valid"` // Valid is true if ConsentSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsentSource) Scan(value interface{}) error {
	if value == nil {
		ns.ConsentSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsentSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsentSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsentSource), nil
}

type ConsentType string

const (
	ConsentTypeActivityTracking          ConsentType = "activity_tracking"
	ConsentTypeMarketing                 ConsentType = "marketing"
	ConsentTypeWhatsappPublication       ConsentType = "whatsapp_publication"
	ConsentTypeRecommendationPublication ConsentType = "recommendation_publication"
	ConsentTypePrivacyPolicy             ConsentType = "privacy_policy"
	ConsentTypeUserAgreement             ConsentType = "user_agreement"
	ConsentTypeTerms                     ConsentType = "terms"
)

func (e *ConsentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsentType(s)
	case string:
		*e = ConsentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsentType: %T", src)
	}
	return nil
}

type NullConsentType struct {
	ConsentType ConsentType `json:"consent_type"`
	Valid       bool        `json:"valid"` // Valid is true if ConsentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsentType) Scan(value interface{}) error {
	if value == nil {
		ns.ConsentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsentType), nil
}

type EventType string

const (
	EventTypeSearch       EventType = "search"
	EventTypeProfileView  EventType = "profile_view"
	EventTypeContactClick EventType = "contact_click"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType `json:"event_type"`
	Valid     bool      `json:"valid"` // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

type MoqBasis string

const (
	MoqBasisTotal     MoqBasis = "total"
	MoqBasisPerDesain MoqBasis = "per_desain"
	MoqBasisPerWarna  MoqBasis = "per_warna"
	MoqBasisOther     MoqBasis = "other"
)

func (e *MoqBasis) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MoqBasis(s)
	case string:
		*e = MoqBasis(s)
	default:
		return fmt.Errorf("unsupported scan type for MoqBasis: %T", src)
	}
	return nil
}

type NullMoqBasis struct {
	MoqBasis MoqBasis `json:"moq_basis"`
	Valid    bool     `json:"valid"` // Valid is true if MoqBasis is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMoqBasis) Scan(value interface{}) error {
	if value == nil {
		ns.MoqBasis, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MoqBasis.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMoqBasis) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MoqBasis), nil
}

type OrderStatus string

const (
	OrderStatusPendingReview OrderStatus = "pending_review"
	OrderStatusAccepted      OrderStatus = "accepted"
	OrderStatusDeclined      OrderStatus = "declined"
	OrderStatusCancelled     OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PublicationStatus string

const (
	PublicationStatusDraft     PublicationStatus = "draft"
	PublicationStatusPublished PublicationStatus = "published"
	PublicationStatusWithdrawn PublicationStatus = "withdrawn"
)

func (e *PublicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PublicationStatus(s)
	case string:
		*e = PublicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PublicationStatus: %T", src)
	}
	return nil
}

type NullPublicationStatus struct {
	PublicationStatus PublicationStatus `json:"publication_status"`
	Valid             bool              `json:"valid"` // Valid is true if PublicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPublicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PublicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PublicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPublicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PublicationStatus), nil
}

type TrafficSource string

const (
	TrafficSourcePublic    TrafficSource = "public"
	TrafficSourceDemo      TrafficSource = "demo"
	TrafficSourceStaffTest TrafficSource = "staff_test"
)

func (e *TrafficSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrafficSource(s)
	case string:
		*e = TrafficSource(s)
	default:
		return fmt.Errorf("unsupported scan type for TrafficSource: %T", src)
	}
	return nil
}

type NullTrafficSource struct {
	TrafficSource TrafficSource `json:"traffic_source"`
	Valid         bool          `json:"valid"` // Valid is true if TrafficSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrafficSource) Scan(value interface{}) error {
	if value == nil {
		ns.TrafficSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrafficSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrafficSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrafficSource), nil
}

type Artist struct {
	ID              uuid.UUID  `json:"id"`
	DisplayName     string     `json:"display_name"`
	EnmasseArtistID *uuid.UUID `json:"enmasse_artist_id"`
}

type Category struct {
	Slug              string            `json:"slug"`
	LabelID           string            `json:"label_id"`
	ShortcutOrder     int32             `json:"shortcut_order"`
	GroupSlug         string            `json:"group_slug"`
	PublicationStatus PublicationStatus `json:"publication_status"`
	Source            string            `json:"source"`
	ProposedByMakerID *uuid.UUID        `json:"proposed_by_maker_id"`
}

type CategoryGroup struct {
	Slug              string            `json:"slug"`
	LabelID           string            `json:"label_id"`
	ShortcutOrder     int32             `json:"shortcut_order"`
	PublicationStatus PublicationStatus `json:"publication_status"`
	Source            string            `json:"source"`
	ProposedByMakerID *uuid.UUID        `json:"proposed_by_maker_id"`
	CreatedAt         time.Time         `json:"created_at"`
}

type CategorySynonym struct {
	ID           uuid.UUID `json:"id"`
	CategorySlug string    `json:"category_slug"`
	Synonym      string    `json:"synonym"`
}

type Consent struct {
	ID            uuid.UUID          `json:"id"`
	UserID        *uuid.UUID         `json:"user_id"`
	AnonSessionID uuid.UUID          `json:"anon_session_id"`
	ConsentType   ConsentType        `json:"consent_type"`
	Version       string             `json:"version"`
	Granted       bool               `json:"granted"`
	GrantedAt     pgtype.Timestamptz `json:"granted_at"`
	WithdrawnAt   pgtype.Timestamptz `json:"withdrawn_at"`
	Source        ConsentSource      `json:"source"`
	IpHash        string             `json:"ip_hash"`
	UserAgentHash string             `json:"user_agent_hash"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type Event struct {
	ID                  uuid.UUID     `json:"id"`
	Type                EventType     `json:"type"`
	TrafficSource       TrafficSource `json:"traffic_source"`
	AnonSessionID       uuid.UUID     `json:"anon_session_id"`
	RawQuery            *string       `json:"raw_query"`
	InterpretedCategory *string       `json:"interpreted_category"`
	MatchedSynonym      *string       `json:"matched_synonym"`
	ResultCount         *int32        `json:"result_count"`
	NoResultReason      *string       `json:"no_result_reason"`
	MakerID             *uuid.UUID    `json:"maker_id"`
	Counted             bool          `json:"counted"`
	CreatedAt           time.Time     `json:"created_at"`
	EnmasseUserID       *uuid.UUID    `json:"enmasse_user_id"`
}

type Maker struct {
	ID                uuid.UUID         `json:"id"`
	Name              string            `json:"name"`
	City              string            `json:"city"`
	PublicationStatus PublicationStatus `json:"publication_status"`
	VerificationDate  *time.Time        `json:"verification_date"`
	MoqQuantity       *int32            `json:"moq_quantity"`
	MoqBasis          NullMoqBasis      `json:"moq_basis"`
	MoqBasisNote      *string           `json:"moq_basis_note"`
	LeadTimeEstimate  *string           `json:"lead_time_estimate"`
	PriceMinIdr       *int32            `json:"price_min_idr"`
	PriceMaxIdr       *int32            `json:"price_max_idr"`
	PriceNote         *string           `json:"price_note"`
	Conditions        *string           `json:"conditions"`
	IsDemoFixture     bool              `json:"is_demo_fixture"`
	EnmasseVendorID   *uuid.UUID        `json:"enmasse_vendor_id"`
	CreatedAt         time.Time         `json:"created_at"`
	UpdatedAt         time.Time         `json:"updated_at"`
	HoursOpen         *string           `json:"hours_open"`
	HoursClose        *string           `json:"hours_close"`
	ServiceArea       *string           `json:"service_area"`
	HoursDays         []string          `json:"hours_days"`
	EnmasseUserID     *uuid.UUID        `json:"enmasse_user_id"`
}

type MakerCapability struct {
	MakerID      uuid.UUID `json:"maker_id"`
	CategorySlug string    `json:"category_slug"`
}

type MakerContact struct {
	ID               uuid.UUID          `json:"id"`
	MakerID          uuid.UUID          `json:"maker_id"`
	Channel          string             `json:"channel"`
	E164Digits       string             `json:"e164_digits"`
	PublishPermitted bool               `json:"publish_permitted"`
	PermissionAt     pgtype.Timestamptz `json:"permission_at"`
}

type MakerMedium struct {
	ID        uuid.UUID `json:"id"`
	MakerID   uuid.UUID `json:"maker_id"`
	Url       string    `json:"url"`
	Alt       string    `json:"alt"`
	SortOrder int32     `json:"sort_order"`
}

type Order struct {
	ID                uuid.UUID          `json:"id"`
	ReferenceCode     string             `json:"reference_code"`
	MakerID           uuid.UUID          `json:"maker_id"`
	EnmasseUserID     uuid.UUID          `json:"enmasse_user_id"`
	EnmasseArtistID   *uuid.UUID         `json:"enmasse_artist_id"`
	ArtistDisplayName string             `json:"artist_display_name"`
	MakerName         string             `json:"maker_name"`
	MakerCity         string             `json:"maker_city"`
	Status            OrderStatus        `json:"status"`
	ProjectName       string             `json:"project_name"`
	ProductName       string             `json:"product_name"`
	CategorySlug      string             `json:"category_slug"`
	Quantity          int32              `json:"quantity"`
	QuantityNote      *string            `json:"quantity_note"`
	DesignCount       int32              `json:"design_count"`
	WantSample        bool               `json:"want_sample"`
	SampleQuantity    *int32             `json:"sample_quantity"`
	RequestedReadyOn  time.Time          `json:"requested_ready_on"`
	RequestedShipOn   time.Time          `json:"requested_ship_on"`
	Rush              bool               `json:"rush"`
	BudgetMinIdr      *int32             `json:"budget_min_idr"`
	BudgetMaxIdr      *int32             `json:"budget_max_idr"`
	Notes             *string            `json:"notes"`
	ShipToProvince    string             `json:"ship_to_province"`
	ShipToCity        string             `json:"ship_to_city"`
	ShipToDistrict    string             `json:"ship_to_district"`
	ShipToAddress     *string            `json:"ship_to_address"`
	VendorNote        *string            `json:"vendor_note"`
	StatusChangedAt   pgtype.Timestamptz `json:"status_changed_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type OrderAttachment struct {
	ID               uuid.UUID `json:"id"`
	OrderID          uuid.UUID `json:"order_id"`
	Url              string    `json:"url"`
	ContentType      string    `json:"content_type"`
	OriginalFilename string    `json:"original_filename"`
	ByteSize         int32     `json:"byte_size"`
	SortOrder        int32     `json:"sort_order"`
	CreatedAt        time.Time `json:"created_at"`
}

type Recommendation struct {
	ID                   uuid.UUID         `json:"id"`
	ArtistID             uuid.UUID         `json:"artist_id"`
	MakerID              uuid.UUID         `json:"maker_id"`
	EnmasseArtistID      *uuid.UUID        `json:"enmasse_artist_id"`
	ProductMade          string            `json:"product_made"`
	ProductionDateApprox string            `json:"production_date_approx"`
	Body                 string            `json:"body"`
	Quantity             *string           `json:"quantity"`
	WouldUseAgain        *bool             `json:"would_use_again"`
	PublicationStatus    PublicationStatus `json:"publication_status"`
	CreatedAt            time.Time         `json:"created_at"`
	UpdatedAt            time.Time         `json:"updated_at"`
}

type Session struct {
	AnonSessionID uuid.UUID  `json:"anon_session_id"`
	EnmasseUserID *uuid.UUID `json:"enmasse_user_id"`
	CreatedAt     time.Time  `json:"created_at"`
	LastFlushAt   time.Time  `json:"last_flush_at"`
}

type StaffUser struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}
