// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMakerByEnmasseUser = `-- name: GetMakerByEnmasseUser :one
SELECT
    m.id,
    m.name,
    m.city,
    m.publication_status,
    m.verification_date,
    m.moq_quantity,
    m.moq_basis,
    m.moq_basis_note,
    m.lead_time_estimate,
    m.price_min_idr,
    m.price_max_idr,
    m.price_note,
    m.conditions,
    m.is_demo_fixture,
    m.enmasse_vendor_id,
    m.enmasse_user_id,
    m.hours_open,
    m.hours_close,
    m.hours_days,
    m.service_area
FROM makers m
WHERE m.enmasse_user_id = $1
LIMIT 1
`

type GetMakerByEnmasseUserRow struct {
	ID                uuid.UUID         `json:"id"`
	Name              string            `json:"name"`
	City              string            `json:"city"`
	PublicationStatus PublicationStatus `json:"publication_status"`
	VerificationDate  *time.Time        `json:"verification_date"`
	MoqQuantity       *int32            `json:"moq_quantity"`
	MoqBasis          NullMoqBasis      `json:"moq_basis"`
	MoqBasisNote      *string           `json:"moq_basis_note"`
	LeadTimeEstimate  *string           `json:"lead_time_estimate"`
	PriceMinIdr       *int32            `json:"price_min_idr"`
	PriceMaxIdr       *int32            `json:"price_max_idr"`
	PriceNote         *string           `json:"price_note"`
	Conditions        *string           `json:"conditions"`
	IsDemoFixture     bool              `json:"is_demo_fixture"`
	EnmasseVendorID   *uuid.UUID        `json:"enmasse_vendor_id"`
	EnmasseUserID     *uuid.UUID        `json:"enmasse_user_id"`
	HoursOpen         *string           `json:"hours_open"`
	HoursClose        *string           `json:"hours_close"`
	HoursDays         []string          `json:"hours_days"`
	ServiceArea       *string           `json:"service_area"`
}

func (q *Queries) GetMakerByEnmasseUser(ctx context.Context, enmasseUserID *uuid.UUID) (GetMakerByEnmasseUserRow, error) {
	row := q.db.QueryRow(ctx, getMakerByEnmasseUser, enmasseUserID)
	var i GetMakerByEnmasseUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.PublicationStatus,
		&i.VerificationDate,
		&i.MoqQuantity,
		&i.MoqBasis,
		&i.MoqBasisNote,
		&i.LeadTimeEstimate,
		&i.PriceMinIdr,
		&i.PriceMaxIdr,
		&i.PriceNote,
		&i.Conditions,
		&i.IsDemoFixture,
		&i.EnmasseVendorID,
		&i.EnmasseUserID,
		&i.HoursOpen,
		&i.HoursClose,
		&i.HoursDays,
		&i.ServiceArea,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, reference_code, maker_id, enmasse_user_id, enmasse_artist_id, artist_display_name, maker_name, maker_city, status, project_name, product_name, category_slug, quantity, quantity_note, design_count, want_sample, sample_quantity, requested_ready_on, requested_ship_on, rush, budget_min_idr, budget_max_idr, notes, ship_to_province, ship_to_city, ship_to_district, ship_to_address, vendor_note, status_changed_at, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ReferenceCode,
		&i.MakerID,
		&i.EnmasseUserID,
		&i.EnmasseArtistID,
		&i.ArtistDisplayName,
		&i.MakerName,
		&i.MakerCity,
		&i.Status,
		&i.ProjectName,
		&i.ProductName,
		&i.CategorySlug,
		&i.Quantity,
		&i.QuantityNote,
		&i.DesignCount,
		&i.WantSample,
		&i.SampleQuantity,
		&i.RequestedReadyOn,
		&i.RequestedShipOn,
		&i.Rush,
		&i.BudgetMinIdr,
		&i.BudgetMaxIdr,
		&i.Notes,
		&i.ShipToProvince,
		&i.ShipToCity,
		&i.ShipToDistrict,
		&i.ShipToAddress,
		&i.VendorNote,
		&i.StatusChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (
    reference_code,
    maker_id,
    enmasse_user_id,
    enmasse_artist_id,
    artist_display_name,
    maker_name,
    maker_city,
    project_name,
    product_name,
    category_slug,
    quantity,
    quantity_note,
    design_count,
    want_sample,
    sample_quantity,
    requested_ready_on,
    requested_ship_on,
    rush,
    budget_min_idr,
    budget_max_idr,
    notes,
    ship_to_province,
    ship_to_city,
    ship_to_district,
    ship_to_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25
)
RETURNING id, reference_code, maker_id, enmasse_user_id, enmasse_artist_id, artist_display_name, maker_name, maker_city, status, project_name, product_name, category_slug, quantity, quantity_note, design_count, want_sample, sample_quantity, requested_ready_on, requested_ship_on, rush, budget_min_idr, budget_max_idr, notes, ship_to_province, ship_to_city, ship_to_district, ship_to_address, vendor_note, status_changed_at, created_at, updated_at
`

type InsertOrderParams struct {
	ReferenceCode     string     `json:"reference_code"`
	MakerID           uuid.UUID  `json:"maker_id"`
	EnmasseUserID     uuid.UUID  `json:"enmasse_user_id"`
	EnmasseArtistID   *uuid.UUID `json:"enmasse_artist_id"`
	ArtistDisplayName string     `json:"artist_display_name"`
	MakerName         string     `json:"maker_name"`
	MakerCity         string     `json:"maker_city"`
	ProjectName       string     `json:"project_name"`
	ProductName       string     `json:"product_name"`
	CategorySlug      string     `json:"category_slug"`
	Quantity          int32      `json:"quantity"`
	QuantityNote      *string    `json:"quantity_note"`
	DesignCount       int32      `json:"design_count"`
	WantSample        bool       `json:"want_sample"`
	SampleQuantity    *int32     `json:"sample_quantity"`
	RequestedReadyOn  time.Time  `json:"requested_ready_on"`
	RequestedShipOn   time.Time  `json:"requested_ship_on"`
	Rush              bool       `json:"rush"`
	BudgetMinIdr      *int32     `json:"budget_min_idr"`
	BudgetMaxIdr      *int32     `json:"budget_max_idr"`
	Notes             *string    `json:"notes"`
	ShipToProvince    string     `json:"ship_to_province"`
	ShipToCity        string     `json:"ship_to_city"`
	ShipToDistrict    string     `json:"ship_to_district"`
	ShipToAddress     *string    `json:"ship_to_address"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ReferenceCode,
		arg.MakerID,
		arg.EnmasseUserID,
		arg.EnmasseArtistID,
		arg.ArtistDisplayName,
		arg.MakerName,
		arg.MakerCity,
		arg.ProjectName,
		arg.ProductName,
		arg.CategorySlug,
		arg.Quantity,
		arg.QuantityNote,
		arg.DesignCount,
		arg.WantSample,
		arg.SampleQuantity,
		arg.RequestedReadyOn,
		arg.RequestedShipOn,
		arg.Rush,
		arg.BudgetMinIdr,
		arg.BudgetMaxIdr,
		arg.Notes,
		arg.ShipToProvince,
		arg.ShipToCity,
		arg.ShipToDistrict,
		arg.ShipToAddress,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ReferenceCode,
		&i.MakerID,
		&i.EnmasseUserID,
		&i.EnmasseArtistID,
		&i.ArtistDisplayName,
		&i.MakerName,
		&i.MakerCity,
		&i.Status,
		&i.ProjectName,
		&i.ProductName,
		&i.CategorySlug,
		&i.Quantity,
		&i.QuantityNote,
		&i.DesignCount,
		&i.WantSample,
		&i.SampleQuantity,
		&i.RequestedReadyOn,
		&i.RequestedShipOn,
		&i.Rush,
		&i.BudgetMinIdr,
		&i.BudgetMaxIdr,
		&i.Notes,
		&i.ShipToProvince,
		&i.ShipToCity,
		&i.ShipToDistrict,
		&i.ShipToAddress,
		&i.VendorNote,
		&i.StatusChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrderAttachment = `-- name: InsertOrderAttachment :one
INSERT INTO order_attachments (
    order_id, url, content_type, original_filename, byte_size, sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, order_id, url, content_type, original_filename, byte_size, sort_order, created_at
`

type InsertOrderAttachmentParams struct {
	OrderID          uuid.UUID `json:"order_id"`
	Url              string    `json:"url"`
	ContentType      string    `json:"content_type"`
	OriginalFilename string    `json:"original_filename"`
	ByteSize         int32     `json:"byte_size"`
	SortOrder        int32     `json:"sort_order"`
}

func (q *Queries) InsertOrderAttachment(ctx context.Context, arg InsertOrderAttachmentParams) (OrderAttachment, error) {
	row := q.db.QueryRow(ctx, insertOrderAttachment,
		arg.OrderID,
		arg.Url,
		arg.ContentType,
		arg.OriginalFilename,
		arg.ByteSize,
		arg.SortOrder,
	)
	var i OrderAttachment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Url,
		&i.ContentType,
		&i.OriginalFilename,
		&i.ByteSize,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderAttachments = `-- name: ListOrderAttachments :many
SELECT id, order_id, url, content_type, original_filename, byte_size, sort_order, created_at FROM order_attachments
WHERE order_id = $1
ORDER BY sort_order, id
`

func (q *Queries) ListOrderAttachments(ctx context.Context, orderID uuid.UUID) ([]OrderAttachment, error) {
	rows, err := q.db.Query(ctx, listOrderAttachments, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderAttachment{}
	for rows.Next() {
		var i OrderAttachment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Url,
			&i.ContentType,
			&i.OriginalFilename,
			&i.ByteSize,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderAttachmentsForOrders = `-- name: ListOrderAttachmentsForOrders :many
SELECT id, order_id, url, content_type, original_filename, byte_size, sort_order, created_at FROM order_attachments
WHERE order_id = ANY ($1::uuid[])
ORDER BY sort_order, id
`

func (q *Queries) ListOrderAttachmentsForOrders(ctx context.Context, orderIds []uuid.UUID) ([]OrderAttachment, error) {
	rows, err := q.db.Query(ctx, listOrderAttachmentsForOrders, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderAttachment{}
	for rows.Next() {
		var i OrderAttachment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Url,
			&i.ContentType,
			&i.OriginalFilename,
			&i.ByteSize,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByArtist = `-- name: ListOrdersByArtist :many
SELECT id, reference_code, maker_id, enmasse_user_id, enmasse_artist_id, artist_display_name, maker_name, maker_city, status, project_name, product_name, category_slug, quantity, quantity_note, design_count, want_sample, sample_quantity, requested_ready_on, requested_ship_on, rush, budget_min_idr, budget_max_idr, notes, ship_to_province, ship_to_city, ship_to_district, ship_to_address, vendor_note, status_changed_at, created_at, updated_at FROM orders
WHERE enmasse_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByArtist(ctx context.Context, enmasseUserID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByArtist, enmasseUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceCode,
			&i.MakerID,
			&i.EnmasseUserID,
			&i.EnmasseArtistID,
			&i.ArtistDisplayName,
			&i.MakerName,
			&i.MakerCity,
			&i.Status,
			&i.ProjectName,
			&i.ProductName,
			&i.CategorySlug,
			&i.Quantity,
			&i.QuantityNote,
			&i.DesignCount,
			&i.WantSample,
			&i.SampleQuantity,
			&i.RequestedReadyOn,
			&i.RequestedShipOn,
			&i.Rush,
			&i.BudgetMinIdr,
			&i.BudgetMaxIdr,
			&i.Notes,
			&i.ShipToProvince,
			&i.ShipToCity,
			&i.ShipToDistrict,
			&i.ShipToAddress,
			&i.VendorNote,
			&i.StatusChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByMaker = `-- name: ListOrdersByMaker :many
SELECT id, reference_code, maker_id, enmasse_user_id, enmasse_artist_id, artist_display_name, maker_name, maker_city, status, project_name, product_name, category_slug, quantity, quantity_note, design_count, want_sample, sample_quantity, requested_ready_on, requested_ship_on, rush, budget_min_idr, budget_max_idr, notes, ship_to_province, ship_to_city, ship_to_district, ship_to_address, vendor_note, status_changed_at, created_at, updated_at FROM orders
WHERE maker_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByMaker(ctx context.Context, makerID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByMaker, makerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceCode,
			&i.MakerID,
			&i.EnmasseUserID,
			&i.EnmasseArtistID,
			&i.ArtistDisplayName,
			&i.MakerName,
			&i.MakerCity,
			&i.Status,
			&i.ProjectName,
			&i.ProductName,
			&i.CategorySlug,
			&i.Quantity,
			&i.QuantityNote,
			&i.DesignCount,
			&i.WantSample,
			&i.SampleQuantity,
			&i.RequestedReadyOn,
			&i.RequestedShipOn,
			&i.Rush,
			&i.BudgetMinIdr,
			&i.BudgetMaxIdr,
			&i.Notes,
			&i.ShipToProvince,
			&i.ShipToCity,
			&i.ShipToDistrict,
			&i.ShipToAddress,
			&i.VendorNote,
			&i.StatusChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2,
    vendor_note = $3,
    status_changed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, reference_code, maker_id, enmasse_user_id, enmasse_artist_id, artist_display_name, maker_name, maker_city, status, project_name, product_name, category_slug, quantity, quantity_note, design_count, want_sample, sample_quantity, requested_ready_on, requested_ship_on, rush, budget_min_idr, budget_max_idr, notes, ship_to_province, ship_to_city, ship_to_district, ship_to_address, vendor_note, status_changed_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID         uuid.UUID   `json:"id"`
	Status     OrderStatus `json:"status"`
	VendorNote *string     `json:"vendor_note"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status, arg.VendorNote)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ReferenceCode,
		&i.MakerID,
		&i.EnmasseUserID,
		&i.EnmasseArtistID,
		&i.ArtistDisplayName,
		&i.MakerName,
		&i.MakerCity,
		&i.Status,
		&i.ProjectName,
		&i.ProductName,
		&i.CategorySlug,
		&i.Quantity,
		&i.QuantityNote,
		&i.DesignCount,
		&i.WantSample,
		&i.SampleQuantity,
		&i.RequestedReadyOn,
		&i.RequestedShipOn,
		&i.Rush,
		&i.BudgetMinIdr,
		&i.BudgetMaxIdr,
		&i.Notes,
		&i.ShipToProvince,
		&i.ShipToCity,
		&i.ShipToDistrict,
		&i.ShipToAddress,
		&i.VendorNote,
		&i.StatusChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
